#spring:
#  datasource:
#    platform: mariadb
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/test?autoReconnect=true
#    username: root
#    password:
    testWhileIdle: true
    #    validationQuery: SELECT 1

#  jpa:
#    ddl-auto: ''